app/models.py
from enum import unique
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from werkzeug.security import generate_password_hash
from flask_login import UserMixin

db = SQLAlchemy()
# create models based off of ERD (Database Tables)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(150), nullable=False, unique=True)
    email = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String(256), nullable=False)
    post = db.relationship('Post',backref='author', lazy=True)

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = generate_password_hash(password)
        

class Post(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(150), nullable=False, unique=True)
    image = db.Column(db.String(300))
    content = db.Column(db.String(300))
    date_created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __init__(self, title, image, content, user_id):
        self.title = title
        self.image = image
        self.content = content
        self.user_id = user_id

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False, unique=True)
    price = db.Column(db.Float())
    image = db.Column(db.String())
    description = db.Column(db.String())
    created_on = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    def __init__(self, name, price, image, description):
        self.name = name
        self.price = price
        self.image = image
        self.description = description

    def to_dict(self):
        return {
            'id' : self.id,
            'name' : self.name,
            'price' : self.price,
            'image' : self.image,
            'description' : self.description,
            'created_on' : self.created_on,
        }

class Pokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False, unique=True)
    image = db.Column(db.String())
    types = db.Column(db.String())

    def __init__(self, name, image, types):
        self.name = name
        self.image = image
        self.types = types

app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,BooleanField,SubmitField
from wtforms.validators import DataRequired

class CreatePostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    image = StringField('Image Url')
    content = StringField('Content', validators=[DataRequired()])
    submit = SubmitField()
    

app/__init__.py
from flask import Flask
from config import Config

# importing blueprint
from .auth.routes import auth
from .blog.routes import blog
from .shop.routes import shop

# importing database
from .models import db, User

# import database related
from flask_migrate import Migrate

# what we use to keep track of all of our logged in users
from flask_login import LoginManager


# instanciating Flask class
app = Flask(__name__)
login = LoginManager()


@login.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app.register_blueprint(auth)
app.register_blueprint(blog)
app.register_blueprint(shop)

# setting configuration for Config class from config and variables in .env folder
app.config.from_object(Config)

# initialize database
db.init_app(app)
login.init_app(app)

migrate = Migrate(app,db)



# registering blueprint

from . import routes
from . import models

app/blog/routes.py
from flask import Blueprint,render_template,request,redirect,url_for
from flask_login import current_user, login_required


from .forms import CreatePostForm
from app.models import Post

blog = Blueprint('blog',__name__,template_folder='blog_templates')

from app.models import db

import requests as r

from app.models import Pokemon

@blog.route('/')
def blogHome():
    posts = Post.query.all()
    return render_template('blog.html' , posts = posts)

@blog.route('/pokebikes')
def pokeBikes():
    data = r.get('https://pokeapi.co/api/v2/item/bicycle/')
    my_data = data.json()
    bikes = [dict['name'] for dict in my_data['names']]
    my_img = my_data['sprites']['default']
    return render_template('pokebikes.html', bikes = bikes, my_img = my_img)


@blog.route('/posts/create', methods=["GET","POST"])
@login_required
def createPost():
    form = CreatePostForm()
    if request.method == "POST":
            if form.validate():
                print('form was validated')
                title = form.title.data
                image = form.image.data
                content = form.content.data

                # create instance of post
                post = Post(title, image, content, current_user.id)
                # add instance of database 
                db.session.add(post)
                # commit to database like github
                db.session.commit()
            
                return redirect(url_for('blog.blogHome'))

    return render_template('createpost.html', form=form)

@blog.route('/search/pokemon', methods=['POST'])
def searchPokemon():
    if request.method == "POST":
        print('request is made')
        my_pokemon = request.form['poke']
        data = data = r.get(f'https://pokeapi.co/api/v2/pokemon/{my_pokemon}')
        if data.status_code == 200:
            my_data = data.json()
            
            pokemon = {
                'name':'',
                'image':'',
                'types': [],
            }
            for type in my_data['types']:
                pokemon['types'].append(type['type']['name'])
            pokemon['name'] = my_data['name']
            pokemon['image'] = my_data['sprites']['front_default']

            name = pokemon['name']
            image = pokemon['image']
            types = pokemon['types']

            pk = Pokemon(name,image,types)

            db.session.add(pk)

            db.session.commit()
            

            # grab information and pass to a template
            return render_template('pokemon.html', pokemon = pokemon)
        else:
            pokemon = ''
            return render_template('pokemon.html', pokemon = pokemon)

    
    return {'hi':'there'}

app/routes.py
from app import app
from flask import render_template

from flask_login import login_required

@app.route('/oldhome')
def home():
    return render_template('index.html', title='Home')

@app.route('/about')
@login_required
def about():
    return render_template('about.html', title='About me')

app/shop/routes.py
from flask import Blueprint,render_template,redirect,url_for, jsonify


from app.models import Product

shop= Blueprint('shop',__name__,template_folder='shop_templates')

from app.models import db

@shop.route('/shop')
def allProducts():
    products = Product.query.all()
    return render_template('shop.html', products = products)

@shop.route('/shop/<int:id>')
def individualProduct(id):
    product = Product.query.filter_by(id=id).first()
    if product is None:
        return redirect(url_for('shop.allProducts'))
    return render_template('product.html', p = product)

@shop.route('/api/shop/products')
def allProductsAPI():
    products = Product.query.all()
    return jsonify([p.to_dict() for p in products])

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>This is the awesome about me page</h1>
{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<title>{{title}}</title>
</head>
<body>
    {% include 'nav.html' %}
    <main class="container">
        {% block content %}

        {% endblock content %}
    </main>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Howdy YA'LL!</h1>

{% endblock content %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Allan's Page</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('shop.allProducts')}}">Shop</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('blog.createPost') }}">Create Post</a>
          </li>
          <li class="nav-item">
            <p class="nav-link" href="#">Hello, {{ current_user.username }}</p>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logMeOut') }}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.logMeIn') }}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.signUp') }}">Sign Up</a>
          </li>
          {% endif %}
          
        </ul>
        <form class="d-flex" action="/search/pokemon"method="POST">
          <input class="form-control me-2" type="search" name='poke' value="{{ request.form['poke'] }}" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
          
          
     



         

          
        